version: '3'

services:
  backend:
    build: backend/
    command: bash -c "pwd && ls -l && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django_saas_backend
    volumes:
      - ./backend:/django-saas-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}

# volumes:
#   volume-name:
#   driver: local
